# Collections for project previews
collections:
  project_previews:
    output: true
    permalink: /projects/preview/:name

# Defaults for project previews
defaults:
  - scope:
      path: "pages/projects/456a2609e0482c10"
      type: "project_previews"
    values:
      layout: "project"
      preview_name: "dreamwellventures"
